spring.application.name=springconsumer
server.port=8082
spring.cloud.aws.sqs.endpoint=http://sqs.us-east-1.localhost.localstack.cloud:4566
spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.credentials.access-key=test
spring.cloud.aws.credentials.secret-key=test